
* Values: Know Why; Innovate Deliberately

  
* Values: Take Ownership; Always Have a Sense of Urgency


* Technical Session- Values: Dive Deep
  

* Technical Session- Values: Love Problems, Not Solutions

----------------


value-based questions => dive deep into your past experiences.

● The inception of your ideas/projects
● The problem you and your team were solving
● The process you followed and why
● The specific actions you took and drove
● The insights that drove your decisions
● The shipped solutions
● The resulting business impact for your team/org/customers.


Technical Sessions

● Proficiency in Python or R
● Statistical analysis and experimentation
● Metrics definition
● Structured problem solving and business understanding


-----


* What was the most useful thing you designed?
  ** Flash ML
  
* Tell me about a time where you (Behavioural questions)
  
* Amazon style interviews
  
* Tell me the most difficult problem you ever faced

  ** Expression evaluation engine
  ** Building oozie configuration from inputs given on the UI
  
* Describe a time you had to use your best judgement.

  ** Understanding why praas was not being successful initially - too much configuration
  Building a small interface
  
  
* How would you evaluate the success of product x?
  
* Why do you want to work at Convoy?
* If you had a campaign to increase referrals for new drivers to the app
  How would you execute it?
  How would you decide the incentive for the refer-er?
  How would you evaluate the campaign?
* In your last performance review, what were your highest scoring and lowest
  scoring areas?
* How would you identify customers that were/have churned?
* Write SQL to describe things going on in this table
  (min/median/mean/max etc of diff columns),
  how would you find the top or worst performing city,
  what is the % of shipments that were matched automatically etc
* 1st round about background, 2nd round about routing problem
* Tell me something you regret about a past job experience?
* How would you calculate the cost of a missed shipment?




• Describe a situation in which you were able to use persuasion to successfully convince someone
to see things your way.
• Describe a time when you were faced with a stressful situation that demonstrated your coping
skills.
• Give me a specific example of a time when you used good judgment and logic in solving a
problem.
• Give me an example of a time when you set a goal and were able to meet or achieve it.
• Tell me about a time when you had to use your presentation skills to influence someone's opinion.
• Give me a specific example of a time when you had to conform to a policy with which you did
not agree.
• Please discuss an important written document you were required to complete.
• Tell me about a time when you had to go above and beyond the call of duty in order to get a job
done.
• Tell me about a time when you had too many things to do and you were required to prioritize
your tasks.
• Give me an example of a time when you had to make a split second decision.
• What is your typical way of dealing with conflict? Give me an example.
• Tell me about a time you were able to successfully deal with another person even when that
individual may not have personally liked you (or vice versa).
• Tell me about a difficult decision you've made in the last year.
• Give me an example of a time when something you tried to accomplish and failed.
• Give me an example of when you showed initiative and took the lead.
• Tell me about a recent situation in which you had to deal with a very upset customer or coworker.
• Give me an example of a time when you motivated others.
• Tell me about a time when you delegated a project effectively.
• Give me an example of a time when you used your fact-finding skills to solve a problem.
• Tell me about a time when you missed an obvious solution to a problem.
• Describe a time when you anticipated potential problems and developed preventive measures.
• Tell me about a time when you were forced to make an unpopular decision.
• Describe a time when you set your sights too high (or too low).   


  _Other Resources_
  
* https://www.pathrise.com/companies/convoy



# MEDIAN SALARY

#+begin_SRC sql

    SET @N := 0;
    SELECT COUNT(*) FROM EMPLOYEE INTO @TOTAL;

    SELECT AVG(SALARY) FROM
    (SELECT SALARY, RANK() OVER (ORDER BY SALARY) AS RANK_
    FROM EMPLOYEE) A
    CASE WHEN MOD(@TOTAL, 2) = 0
         THEN A.RANK_ IN  (@TOTAL/2, (@TOTAL/2+1))
    ELSE A.RANK_ = (@TOTAL)/2
    END

#+end_SRC


# PIVOTING

** Tables

 - Occupations

   | Column     | Type   |
   |------------+--------|
   | Name       | String |
   | Occupation | String |

 - Sample Input

   | Name      | Occupation |
   |-----------+------------|
   | Samantha  | Doctor     |
   | Julia     | Actor      |
   | Maria     | Actor      |
   | Meera     | Singer     |
   | Ashley    | Professor  |
   | Ketty     | Professor  |
   | Christeen | Professor  |
   | jane      | Actor      |
   | Jenny     | Doctor     |
   | Priya     | Singer     |
   |-----------+------------|
   
- Output

  Jenny    Ashley     Meera  Jane
  Samantha Christeen  Priya  Julia
  NULL     Ketty      NULL   Maria

#+begin_SRC sql
set @r1=0, @r2=0, @r3=0, @r4=0;

Select min(Doctor), min(Professor), min(Singer), min(Actor)
from (
SELECT case 
     	when Occupation='Doctor' then (@r1:=@r1+1)
        when Occupation='Professor' then (@r2:=@r2+1)
        when Occupation='Singer' then (@r3:=@r3+1)
        when Occupation='Actor' then (@r4:=@r4+1) end as RowNumber,
       case
        when Occupation='Doctor' then Name
       end
        as Doctor,
       case
        when Occupation='Professor' then Name
       end
        as Professor,
       case
        when Occupation='Singer' then Name
       end
        as Singer,
       case
        when Occupation='Actor' then Name
       end
        as Actor
  FROM OCCUPATIONS
order by Name
) temp
group by RowNumber;

#+end_SRC

